name: Ruby on Rails CI/CD

on: [push, pull_request]

jobs:
  CI-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start PostgreSql
        run: sudo service postgresql start
      - name: Install bundle
        run: sudo gem install bundler:1.17.2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop -c .rubocop.yml
      # - name: Rspec
      #   run: |
      #         cd server
      #         DATABASE_USERNAME=root DATABASE_PASSWORD=root DEVELOPMENT_DATABASE_NAME=server_development TEST_DATABASE_NAME=server_test bundle exec rails db:create
      #         DATABASE_USERNAME=root DATABASE_PASSWORD=root DEVELOPMENT_DATABASE_NAME=server_development TEST_DATABASE_NAME=server_test HOST_EMAIL=noreply@example.com HOST=localhost:3000 MAIL_USER_NAME=05bcc6a3209edc MAIL_PASSWORD=92b511f145e80b MAIL_ADDRESS=smtp.mailtrap.io MAIL_DOMAIN=smtp.mailtrap.io MAIL_PORT=587 bundle exec rspec
